language: java
sudo: true
jdk: openjdk8
install: true
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
after_success:
- "./gradlew jacocoTestReport coveralls"
notifications:
  webhooks:
    on_success: always
    on_failure: always
    on_start: false
